import Head from 'next/head';
import Link from 'next/link';
import React, { useEffect, useRef, useState } from 'react'
import { HiMenu } from 'react-icons/hi';
import { AiFillCloseCircle } from "react-icons/ai";

import Sidebar from './Sidebar';
import { useRouter } from 'next/router';
import { useDispatch, useSelector } from 'react-redux';
// import { getUserInfo } from '../store/login/loginActions';
import { useSession } from 'next-auth/react';
import { onAuthStateChanged, signOut } from 'firebase/auth';
import { auth } from '../config/firebase';
import Image from 'next/image';


const Layout = ({ children }) => {
  const scrollRef = useRef(null);
  const router = useRouter();
  const [toggleSidebar, setToggleSidebar] = useState(false);
  const dispatch = useDispatch();

  const { data: session } = useSession();

  useEffect(() => {
    scrollRef?.current?.scrollTo(0, 0);
  }, []);

  return (
    <div>
      <Head>
        <title>ShareMe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {session ? (
          <div className="flex bg-gray-50 md:flex-row flex-col h-screen transition-all duration-75 ease-out">
            <div className="hidden md:flex h-screen flex-initial">
              <Sidebar />
            </div>

            <div className="flex md:hidden flex-row">
              <div className="flex flex-row justify-between items-center w-full p-2 shadow-md">
                <HiMenu
                  fontSize={40}
                  className="cursor-pointer"
                  onClick={() => setToggleSidebar(true)}
                />

                <Link href="/">
                  <a>
                    <img
                      src={"/assets/logo.png"}
                      alt="user"
                      className="w-24"
                    />
                  </a>
                </Link>

                <Link href={`/user-profile/${session.user.uid}`}>
                  <a>
                    <img
                      src={session.user.image}
                      alt="user"
                      className="rounded-full w-10"
                    />
                  </a>
                </Link>
              </div>

              {toggleSidebar && (
                <div className="fixed w-4/5 bg-white h-screen overflow-y-auto shadow-md z-50 animate-slide-in">
                  <div className="absolute w-full flex justify-end items-center p-2">
                    <AiFillCloseCircle
                      fontSize={30}
                      className="cursor-pointer"
                      onClick={() => setToggleSidebar(false)}
                    />
                  </div>
                  <Sidebar />
                </div>
              )}
            </div>

            <div
              className="flex-1 pb-2 h-screen overflow-y-scroll"
              ref={scrollRef}
            >
              {children}
            </div>
          </div>
        ) : (
          <>{children}</>
        )}
      </main>
    </div>
  );
}

export default Layout